- name: download peco source
  get_url:
    url=https://github.com/peco/peco/releases/download/{{ peco_version }}/peco_linux_amd64.tar.gz
    dest="/tmp/peco_linux_amd64.tar.gz"

- name: remove tmp dir for peco, if exists
  file:
    path: "/tmp/peco_linux_amd64"
    state: absent

- name: create tmp dir for peco
  file:
    path: "/tmp/peco_linux_amd64"
    state: directory
    mode: 0755

- name: extract peco source
  unarchive:
    src="/tmp/peco_linux_amd64.tar.gz"
    dest="/tmp/peco_linux_amd64"
    copy=no

- name: install peco
  shell: >
    {{ item }}
    chdir="/tmp/peco_linux_amd64/peco_linux_amd64"
    creates="{{ bin_dir }}/peco"
  with_items:
    - cp peco {{ bin_dir }}

- name: clean up tmp dir for peco
  file:
    path: "/tmp/peco_linux_amd64"
    state: absent
